stages:
  - build
  #- test
  - deploy

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

# Cache Maven dependencies
cache:
  paths:
    - .m2/repository

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

build:
  stage: build
  image: maven:3.8.3-openjdk-17
  script:
    - mvn -f pom.xml clean package -DskipTests
  artifacts:
    paths:
      - target/

#test:
 # stage: test
  #image: maven:3.8.3-openjdk-17
  #script:
   # - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  image: alpine:latest
  #before_script:
   # - apk add --no-cache openssh
  script:
    - ssh $SSH_USER@$VM_IPADDRESS 'docker-compose down && docker-compose up'
    #- scp -o StrictHostKeyChecking=no target/*.jar $SSH_USER@$VM_IPADDRESS:/qcm_app
    #- ssh $SSH_USER@$VM_IPADDRESS 'docker-compose down && docker-compose up'
  only:
    - cyr_dev
