stages:
  - deploy

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -


deploy:
  stage: deploy
  image: alpine:latest
  script:
     - ssh $SSH_USER@$VM_IPADDRESS '
        echo "Navigating to qcm_app directory" &&
        cd qcm_app &&
        echo "Pulling latest changes from Git" &&
        git pull &&
        echo "Stopping and removing existing Docker containers" &&
        docker-compose down --remove-orphans && 
        echo "Deleting maven:latest image" &&
        docker rmi maven:latest --force &&
        echo "Deleting old images" &&
        images=$(docker images -a -q); if [ -n "$images" ]; then docker rmi $images; else echo "No Docker images to remove"; fi &&
        echo "Building and starting Docker containers" &&
        docker-compose up --build -d
      '
    #- ssh $SSH_USER@$VM_IPADDRESS "cd qcm_app && git pull && docker-compose down &&  docker-compose up --build -d"
  only:
    - master
