stages:
  - deploy

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -


deploy:
  stage: deploy
  image: alpine:latest
  script:
    - ssh $SSH_USER@$VM_IPADDRESS "cd qcm_app && git pull && docker-compose down &&  docker-compose up"
  only:
    - cyr_dev
