stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

# Cache Maven dependencies
cache:
  paths:
    - .m2/repository

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - ./add_ssh_key.sh

build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:dind
  script:
    - docker build -t qcmapp .
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  image: maven:3.8.3-openjdk-17
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --no-cache openssh
    - ./add_ssh_key.sh
    - docker save qcmapp | bzip2 | ssh -o StrictHostKeyChecking=no $SSH_USER@$VM_IPADDRESS 'bunzip2 | docker load'
    - ssh $SSH_USER@$VM_IPADDRESS 'docker-compose down && docker-compose up -d'
  only:
    - cyr_dev
