version: "3.8"
services:
  api:
    build: .
    restart: always
    ports:
      - 8080:8080
    container_name: mcq_api
    environment:
      MYSQL_DATABASE: mcq_api_db
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_HOST: mysqldb

    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2
  mysqldb:
    container_name: mysqldb
    image: 'mysql:latest'
    restart: always
    ports:
      - 3306:3306

    environment:
      MYSQL_DATABASE: mcq_api_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin