version: "3.8"
services:
  mcq_api:
    restart: on-failure
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_DATABASE: mcq_api_db
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_HOST: database
    depends_on:
      - database
    volumes:
      - .m2:/root/.m2
  database:
    image: 'mysql:latest'
    restart: always
    ports:
      - 3306:3306

    environment:
      MYSQL_DATABASE: mcq_api_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin